name: Linux
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        bt: [Debug, Release]
        cc: [gcc, clang]

    env:
      CC: ${{ matrix.cc }}

    steps:
    - uses: actions/checkout@v7

    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.bt }}

    - name: Build
      run: cmake --build build

    - name: Test
      run: python3 tests/run_tests --build-dir build --verbose
